DROP TABLE IF EXISTS TBL_ASSIGNMENT;
 DROP TABLE IF EXISTS TBL_ASSIGNMENT_STUDENT;

CREATE TABLE TBL_ASSIGNMENT (
  assignment_id INT AUTO_INCREMENT  PRIMARY KEY,
  assignment_name VARCHAR(250) NOT NULL
 );

CREATE TABLE TBL_ASSIGNMENT_STUDENT (
  map_id INT AUTO_INCREMENT  PRIMARY KEY,
  assignment_id INT,
  student_id INT,
  marks INT
 );